### ISSUE TITLE
Allow string as a template data

### ISSUE THREAD

**Issue by daniel-werner** [42coders/document-templates#14]
Currently it is not possible to pass simple string(or any basic type e.g integer) as a template data, only array or objects

**Comment by millsoft** [comment]
This would be awesome. I have a template which comes from a textarea, which is data from users.signature_template -> I want to be able to read it by myself as a string and use document-templates with the string.

**Comment by daniel-werner** [comment]
@millsoft The just released version 2.3.0 adds support for this.
