### ISSUE TITLE
This Project cost me 3 full days of work + CPU time :-/

### ISSUE THREAD

**Issue by hopeseekr** [42coders/document-templates#24]
I have a regrettable tale concerning this project :-/

I am the maintainer of Bettergist. It's my sworn mission to test and catalog the code quality fitness of every single package on packagist.org.

I recently finished v2.0 and got to the point where it was ready to start combing thru every project, checking them out from GitHub/et. al, running `composer install`, and then a smattering of analyses, including phpunit and phpstan.

After much trial, error, and sweat equity, it finally was running unchecked. It took 3 days, because I was running PHPUnit against every major version of PHP 7.1 thru 8.0.

I had catelogged packagist stats and code stats (lines of code, cyclometic complexity, etc.) of exactly 112,991 packages (everything up to `L`), which took about a full day itself.

It did the first 765 projects pretty successfully.

Then, all of a sudden, I received this startling error:

```Postgres: TABLE "packages" DOES NOT EXIST```

**WELLL!!!! THAT WAS CERTAINLY UNEXPECTED!!!**

I launched `psql bettergist` and did a `\d+` and to my abject horror, there were only two tables:

```
bettergist=> \d+
                           List of relations
 Schema |        Name        |   Type   |  Owner   |    Size    | Description 
--------+--------------------+----------+----------+------------+-------------
 public | migrations         | table    | phppro   | 8192 bytes | 
 public | migrations_id_seq  | sequence | phppro   | 8192 bytes | 
 public | document_templates | table    | phppro   | 8192 bytes |
```

Since I was still processing packages in small batches, I knew for sure that the package's vendor started with a `4`. In a few more minutes, I had narrowed it down to this package.

I'm still *very* much confused on how a phpunit subprocess in a different PWD managed to grab my Laravel-Zero project's `.env`, but it did...

I am not going to fault you or anything. My project is way on the leading vanguard of human progress, and I have Laravel projects myself which would have tripped this up.

My main reason for writing this is as a cautionary tale: Frequently backup databases so you cannot possibly lose critical work.

I now have a `/etc/cron.hourly/bettergist-backup`:

```bash
#!/bin/bash

cd /code/bettergist-collector
sudo -u postgres pg_dump bettergist > xz -9 --threads=0 > bettergist-$(date +"%Y%m%d.%H").sql.xz
```

So when this happens again, somewhere among the other 260,000+ composer packages, I'll be ready ;-)

-----

Oh oh! I solved the problem of your project (and others) hijacking my `.env` and database by doing all analysis from within a `docker` image, using my [**phpexperts/dockerize-php**](https://github.com/phpexpertsinc/dockerize-php) project. It can't even connect to the host's postgresql database and no package can manipulate anything other than redis. All file system changes disappear when the docker container stops running.

**Comment by daniel-werner** [comment]
@hopeseekr Thanks for notifying us. Do you know what caused this issue?
